services:
  dumper:
    image: $CUSTOM_IMAGE
    volumes: 
      - "./persist:/mnt"
    environment:
      - WSO2_MYSQL_SERVICE_NAME=mysql
      - WSO2_MYSQL_PORT=3306
      - WSO2_MYSQL_USER=user1
      - WSO2_MYSQL_PASSWORD=password123
      - WSO2IS_DB=db1
      - WSO2_BACKUP_DIR=wso2
      - WSO2UM_DB=db1
      - MYSQL_CRON_PATTERN=0 6 * * *
      - BACKUP_TIME=7
      - REMOTE_BACKUP=true
      - REMOTE_HOST=10.107.148.24
      - REMOTE_DIR=/home/ddd
      - REMOTE_SERVER_PORT=22
      - REMOTE_USER=user
